name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
         args: >
           -Dsonar.organization=barrettonashum8
           -Dsonar.projectKey=barrettonashum8_reactapp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
